name:  Ejecutar Job de Databricks
description: Llena este formulario para ejecutar un job de Databricks
title: "[Job Request] "
labels: ["databricks-run"]
body:
  - type: markdown
    attributes:
      value: |
        ## Configuraci贸n del Job
        Por favor, completa los siguientes campos para ejecutar tu job de Databricks.

  - type: input
    id: target_project
    attributes:
      label: Nombre del Proyecto
      description: Nombre del proyecto o repositorio (para referencia)
      placeholder: cemm-pilotos
    validations:
      required: true

  - type: input
    id: databricks_job_id
    attributes:
      label: ID del Job de Databricks
      description: El ID num茅rico del job en Databricks
      placeholder: "12345"
    validations:
      required: true

  - type: dropdown
    id: execution_type
    attributes:
      label: Tipo de Ejecuci贸n
      description: Selecciona c贸mo quieres ejecutar el job
      options:
        - periodo_unico
        - rango_periodo
      default: 0
    validations:
      required: true

  - type: input
    id: periodo_unico
    attributes:
      label: Periodo nico
      description: Solo si elegiste "periodo_unico". Formato YYYYMM (ejemplo 202504)
      placeholder: "202504"

  - type: input
    id: periodo_inicio
    attributes:
      label: Periodo de Inicio
      description: Solo si elegiste "rango_periodo". Formato YYYYMM (ejemplo 202501)
      placeholder: "202501"

  - type: input
    id: periodo_fin
    attributes:
      label: Periodo de Fin
      description: Solo si elegiste "rango_periodo". Formato YYYYMM (ejemplo 202504)
      placeholder: "202504"

  - type: markdown
    attributes:
      value: |
        ---
        ## 锔 Recordatorios
        
        - Aseg煤rate de tener los scripts de validaci贸n en `scripts/`
        - Verifica que los secretos `DATABRICKS_HOST` y `DATABRICKS_TOKEN` est茅n configurados